export default {
  FETCH: 'pay/FETCH',
  FETCH_FAILED: 'pay/FETCH_FAILED',
  FETCH_SUCCESS: 'pay/FETCH_SUCCESS',
  CREATE: 'pay/CREATE',
  CREATE_FAILED: 'pay/CREATE_FAILED',
  CREATE_SUCCESS: 'pay/CREATE_SUCCESS',
  REMOVE: 'pay/REMOVE',
  REMOVE_FAILED: 'pay/REMOVE_FAILED',
  REMOVE_SUCCESS: 'pay/REMOVE_SUCCESS',
};
