export default {
  FETCH: 'phones/FETCH',
  FETCH_FAILED: 'phones/FETCH_FAILED',
  FETCH_SUCCESS: 'phones/FETCH_SUCCESS',
  CREATE: 'phones/CREATE',
  CREATE_FAILED: 'phones/CREATE_FAILED',
  CREATE_SUCCESS: 'phones/CREATE_SUCCESS',
  REMOVE: 'phones/REMOVE',
  REMOVE_FAILED: 'phones/REMOVE_FAILED',
  REMOVE_SUCCESS: 'phones/REMOVE_SUCCESS',
};
