export default {
  FETCH: 'model/FETCH',
  FETCH_FAILED: 'model/FETCH_FAILED',
  FETCH_SUCCESS: 'model/FETCH_SUCCESS',
  CREATE: 'model/CREATE',
  CREATE_FAILED: 'model/CREATE_FAILED',
  CREATE_SUCCESS: 'model/CREATE_SUCCESS',
  REMOVE: 'model/REMOVE',
  REMOVE_FAILED: 'model/REMOVE_FAILED',
  REMOVE_SUCCESS: 'model/REMOVE_SUCCESS',
};
